# Generated by Django 5.0 on 2023-12-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_notice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'permissions': (('can_upload_notice', 'Can upload notice'),)},
        ),
    ]
