# Generated by Django 5.0.3 on 2024-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_notice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='keywords',
            field=models.ManyToManyField(default=None, null=True, to='home.noticekeywords', verbose_name='Notice Keywords'),
        ),
    ]
