# Generated by Django 5.0.3 on 2024-03-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_noticekeywords_notice_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='keywords',
            field=models.ManyToManyField(default=None, to='home.noticekeywords', verbose_name='Notice Keywords'),
        ),
    ]
