# Generated by Django 5.0.3 on 2024-03-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_notice_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='keywords',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='home.noticekeywords', verbose_name='Notice Keywords'),
        ),
    ]
