# Generated by Django 5.0.3 on 2024-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_noticekeywords_noticekeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='keywords',
            field=models.ManyToManyField(to='home.noticekeyword', verbose_name='Notice Keywords'),
        ),
    ]
