# Generated by Django 5.0.3 on 2024-04-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_notice_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('keywords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.noticekeyword', verbose_name='Notice Keywords')),
            ],
        ),
    ]
