# Generated by Django 5.0.3 on 2024-04-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
